### ISSUE TITLE
Decay option (multi-user manage)

### ISSUE THREAD

**Issue by VeRychard** [wyvern800/tldkp#2]
To implement decay (as in people losing a set percent of their DKP every now and then, for instance weekly) I think the manage command could have the first user param to be set to "all" so everyone who has DKP record will be affected and amount should accept percentage.

If it could be automated, even better :)

Keep up the good work!

**Comment by wyvern800** [comment]
I think i've understood, but I still need some more info, would it be nice to have a set of commands like:
- setdecay <percentage/int> <period (in days)> - Then a cron would work seamleslly to automatize the decaying proccess of people, 
- decay <enable/disable> - Self explanatory

Something like that would work?

**Comment by VeRychard** [comment]
yea, it sounds like it covers all the needs regarding decay 👌

**Comment by wyvern800** [comment]
I've implemented the feature, will be deploying tomorrow after some tests;

I've added one more command, which is the /decay-minimum-cap, which sets a minimum cap for the decay system to remove. that way you can have more control
