### ISSUE TITLE
Check command for all

### ISSUE THREAD

**Issue by VeRychard** [wyvern800/tldkp#3]
As a guild leader it would be nice to have the check command with "all" param to list everyone's DKP values.

**Comment by wyvern800** [comment]
I don't know if you've seen, I've implemented a section in the website that you can have that information, but I can also implement that command. Thanks again <3

![image](https://github.com/user-attachments/assets/4199bba6-08fd-4657-96fd-b0c1c263b7dd)

**Comment by VeRychard** [comment]
uuu, awesome, didn't see the login button before, this is very good. 
can the members see stuff if they log in here as well? or only the admin of discord?
